# Generated by Django 4.1.7 on 2023-03-14 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contents',
            fields=[
                ('level', models.IntegerField(default=0, null=True)),
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(default='', max_length=1000)),
                ('link', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='thumbnail',
            fields=[
                ('card_number', models.IntegerField(null=True)),
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(default=None, max_length=100)),
                ('course_image', models.ImageField(upload_to='thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1', models.BooleanField(default=False)),
                ('card2', models.BooleanField(default=False)),
                ('card3', models.BooleanField(default=False)),
                ('card4', models.BooleanField(default=False)),
                ('card5', models.BooleanField(default=False)),
                ('card6', models.BooleanField(default=False)),
                ('card7', models.BooleanField(default=False)),
                ('card8', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
