# Generated by Django 4.1.7 on 2023-03-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentalist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='slug',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mentalist.contents'),
        ),
    ]
